### ISSUE TITLE
Unexpected error when trying to login with disabled user

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#29]
- create new project
- launch app
- create disabled user:
![image](https://user-images.githubusercontent.com/6158807/99828129-fcf3c680-2b73-11eb-860e-d6ee012180de.png)

- try to login with this user.
Unexpected error is shown:
![image](https://user-images.githubusercontent.com/6158807/99828183-0e3cd300-2b74-11eb-8dfc-96895bc9d452.png)

```
2020-11-20 21:01:48.183 ERROR 66029 --- [nio-8080-exec-8] i.j.u.exception.DefaultExceptionHandler  : Unhandled exception

org.springframework.security.authentication.LockedException: User account is locked
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider$DefaultPreAuthenticationChecks.check(AbstractUserDetailsAuthenticationProvider.java:325) ~[spring-security-core-5.4.1.jar:5.4.1]
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:146) ~[spring-security-core-5.4.1.jar:5.4.1]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-5.4.1.jar:5.4.1]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:201) ~[spring-security-core-5.4.1.jar:5.4.1]
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:510) ~[spring-security-config-5.4.1.jar:5.4.1]
	at io.jmix.securityui.authentication.LoginScreenAuthenticationSupport.authenticate(LoginScreenAuthenticationSupport.java:114) ~[jmix-security-ui-0.2.0-SNAPSHOT.jar:na]
	at com.company.fresh2.screen.login.LoginScreen.login(LoginScreen.java:84) ~[main/:na]
	at com.company.fresh2.screen.login.LoginScreen.onSubmitActionPerformed(LoginScreen.java:69) ~[main/:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.action.BaseAction.actionPerform(BaseAction.java:220) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.FrameActionsHolder.handleAction(FrameActionsHolder.java:161) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at com.vaadin.event.ActionManager.handleAction(ActionManager.java:252) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at com.vaadin.event.ActionManager.handleActions(ActionManager.java:235) ~[vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]
	at io.jmix.ui.widget.JmixOrderedActionsLayout.changeVariables(JmixOrderedActionsLayout.java:88) ~[jmix-ui-0.2.0-SNAPSHOT.jar:na]
	at com.vaadin.server.communication.ServerRpcHandler.changeVariables(ServerRpcHandler.java:611) [vaadin-server-8.9.2-5-jmix.jar:8.9.2-5-jmix]

```

**Comment by andreysubbotin** [comment]
Compilation failed:
```
/src/main/java/com/company/testappl/screen/login/LoginScreen.java:88: error: cannot find symbol
        } catch (BadCredentialsException | DisabledException e) {
                                           ^
  symbol:   class DisabledException
  location: class LoginScreen
1 error

```
