### ISSUE TITLE
Ability to use default interface method to define PredicateRowLevelPolicy

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-security#41]
Current implementation expects a static method, but static method is not inherited when combining roles in an aggregated role, e.g:

```
@Role(name = "CustomerNonConfidentialAccessRole", code = "CustomerNonConfidentialAccessRole")
public interface CustomerNonConfidentialAccessRole {
// ...
    @PredicateRowLevelPolicy(entityClass = CustomerDetail.class, actions = {RowLevelPolicyAction.READ})
    static Predicate<CustomerDetail> customerDetailNotConfidential() {
        return customerDetail -> !Boolean.TRUE.equals(customerDetail.getConfidential());
    }
}

@Role(name = "Salesperson", code = "salesperson-aggr")
public interface SalespersonRole extends
        CustomerNonConfidentialAccessRole,
        OrderRestrictedAccessRole,
        OrdersCreatedByMeOnlyRole,
        SameRegionOnlyRole
{
}
```

If I make the `customerDetailNotConfidential()` method default, I get the exception:
```
Caused by: java.lang.NullPointerException: null

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
	at io.jmix.security.impl.role.builder.extractor.PredicateRowLevelPolicyExtractor.extractRowLevelPolicies(PredicateRowLevelPolicyExtractor.java:54) ~[jmix-security-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.security.impl.role.builder.AnnotatedRoleBuilderImpl.createRole(AnnotatedRoleBuilderImpl.java:71) ~[jmix-security-0.3.0-SNAPSHOT.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_242]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[na:1.8.0_242]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_242]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_242]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_242]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_242]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_242]
	at io.jmix.security.impl.role.provider.AnnotatedRoleProvider.<init>(AnnotatedRoleProvider.java:47) ~[jmix-security-0.3.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_242]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[spring-beans-5.3.1.jar:5.3.1]
	... 51 common frames omitted
```

**Comment by maistrenkoIulia** [comment]
fixed
