### ISSUE TITLE
IllegalArgumentException: entity is null in RoleAssignmentFragment

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-security#49]
```
Caused by: java.lang.IllegalArgumentException: entity is null
	at io.jmix.core.common.util.Preconditions.checkNotNullArgument(Preconditions.java:101) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.EntityStates.isNew(EntityStates.java:71) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.securityui.screen.roleassignment.RoleAssignmentFragment.onAfterShow(RoleAssignmentFragment.java:96) ~[jmix-security-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170) ~[jmix-core-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:58) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.fireScreenAfterShowEvent(ScreensImpl.java:1355) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:395) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.screen.Screen.show(Screen.java:306) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.action.list.EditAction.execute(EditAction.java:366) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.action.list.EditAction.actionPerform(EditAction.java:313) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.AbstractTable.handleClickAction(AbstractTable.java:1381) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at io.jmix.ui.component.impl.AbstractTable.lambda$initComponent$db766529$1(AbstractTable.java:1119) ~[jmix-ui-0.3.0-SNAPSHOT.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
```

**Comment by andreysubbotin** [comment]
Won't fix. Because the RoleAssignment fragment is used from the User editor. RoleAssignment is a separate screen. It's a project with outdated user screen.
