### ISSUE TITLE
endpointClass cannot be null in backoffice UI with oauth2-starter added

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-security#90]
1.0.0-SNAPSHOT
* Open the following project https://github.com/jmix-projects/scr-jmix, OR install the following dependencies to any jmix project
```
    implementation "io.jmix.security:jmix-security-oauth2-starter"
    implementation "io.jmix.graphql:jmix-graphql-starter"
    runtimeOnly "com.graphql-java-kickstart:graphiql-spring-boot-starter:8.1.1"
    implementation 'io.jmix.rest:jmix-rest-starter'
```
* Start the app and open backoffice UI (http://localhost:8080/#login)

The following exception is thrown
```
java.lang.ExceptionInInitializerError: null
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.init(WsHttpUpgradeHandler.java:122) ~[tomcat-embed-websocket-9.0.46.jar:9.0.46]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:940) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.lang.IllegalArgumentException: endpointClass cannot be null
	at javax.websocket.server.ServerEndpointConfig$Builder.<init>(ServerEndpointConfig.java:314) ~[javax.websocket-api-1.1.jar:1.1]
	at javax.websocket.server.ServerEndpointConfig$Builder.create(ServerEndpointConfig.java:287) ~[javax.websocket-api-1.1.jar:1.1]
Caused by: java.lang.IllegalArgumentException: endpointClass cannot be null
```

It seems web-sockets do not workf

**Comment by andreysubbotin** [comment]
Use `graphiql-spring-boot-starter` with excluded dependencies:
```
runtimeOnly ("com.graphql-java-kickstart:graphql-spring-boot-starter:8.1.1") {
    exclude group: 'javax.websocket', module: 'javax.websocket-api'
}
```
